[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[test]
startup_wait = 10000

[programs.localnet]
token_22_staking = "5A7TtjXXH47vAKee3rB866hBdK4PKi9QeUAQZ4U3fvMs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kavindumadushanka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
